"""Append batch-coded registry, segments, and observations."""

from __future__ import annotations

import csv
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
ACCESS = date.today().isoformat()
INVALID_DOC = "chapter-based or promotional footage; timing for workflow reference only"
INVALID_MONTAGE = "narrated montage not real-time task duration"
INVALID_M05 = "parallel M01 upload; bounds scaled from M01 transcript alignment"


def write_csv(path: Path, fieldnames: list[str], rows: list[dict]) -> None:
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def read_csv(path: Path) -> tuple[list[str], list[dict]]:
    with path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        return list(reader.fieldnames or []), list(reader)


def main() -> None:
    meta_fields, meta_rows = read_csv(DATA / "video_metadata.csv")

    updates = {
        "R01": {
            "source_name": "BrightMaster Robotics",
            "total_video_duration": "n/a",
            "visibility_quality": "n/a",
            "coding_confidence": "high",
            "inclusion_status": "include_pool",
            "score_relevance": "2",
            "score_visual_clarity": "n/a",
            "score_activity_continuity": "n/a",
            "score_activity_identifiability": "2",
            "score_interaction_visibility": "n/a",
            "score_editing_level": "n/a",
            "score_parameter_measurability": "2",
            "suitability_total_score": "n/a",
            "suitability_band": "source_pool",
            "notes": "17 channel videos catalogued; individual robot videos coded as R05-R08",
        },
        "R03": {
            "source_name": "JobToRob",
            "total_video_duration": "14",
            "visibility_quality": "medium",
            "coding_confidence": "low",
            "inclusion_status": "exclude",
            "score_relevance": "1",
            "score_visual_clarity": "1",
            "score_activity_continuity": "1",
            "score_activity_identifiability": "1",
            "score_interaction_visibility": "0",
            "score_editing_level": "1",
            "score_parameter_measurability": "0",
            "suitability_total_score": "5",
            "suitability_band": "exclude",
            "notes": "14s clip; manufacturer not verified as BrightMaster",
        },
        "M03": {
            "source_name": "Engineering Motive",
            "total_video_duration": "410",
            "visibility_quality": "high",
            "coding_confidence": "medium",
            "inclusion_status": "include",
            "score_relevance": "2",
            "score_visual_clarity": "2",
            "score_activity_continuity": "1",
            "score_activity_identifiability": "2",
            "score_interaction_visibility": "1",
            "score_editing_level": "1",
            "score_parameter_measurability": "2",
            "suitability_total_score": "11",
            "suitability_band": "structured_extraction",
            "notes": "Educational components and process overview with YouTube chapters",
        },
        "M04": {
            "source_name": "unknown",
            "total_video_duration": "n/a",
            "visibility_quality": "n/a",
            "coding_confidence": "medium",
            "inclusion_status": "include_pool",
            "score_relevance": "2",
            "score_visual_clarity": "n/a",
            "score_activity_continuity": "n/a",
            "score_activity_identifiability": "2",
            "score_interaction_visibility": "n/a",
            "score_editing_level": "n/a",
            "score_parameter_measurability": "2",
            "suitability_total_score": "n/a",
            "suitability_band": "source_pool",
            "notes": "Playlist pool for future individual screening",
        },
    }
    for row in meta_rows:
        if row["video_id"] in updates:
            row.update(updates[row["video_id"]])

    new_meta = [
        {
            "video_id": "R05",
            "video_url": "https://www.youtube.com/watch?v=js3ftGNLsPY",
            "video_category": "robot",
            "platform": "YouTube",
            "title": "06-Floor Coating Robot",
            "source_name": "Brightmasterrobotics_BMR",
            "access_date": ACCESS,
            "activity_focus": "concrete_finishing,coating",
            "construction_context": "indoor_slab",
            "total_video_duration": "60",
            "visibility_quality": "high",
            "coding_confidence": "medium",
            "inclusion_status": "include",
            "score_relevance": "2",
            "score_visual_clarity": "2",
            "score_activity_continuity": "2",
            "score_activity_identifiability": "2",
            "score_interaction_visibility": "1",
            "score_editing_level": "1",
            "score_parameter_measurability": "1",
            "suitability_total_score": "11",
            "suitability_band": "structured_extraction",
            "notes": "Official BrightMaster floor coating demo",
        },
        {
            "video_id": "R06",
            "video_url": "https://www.youtube.com/watch?v=vP2Csqu_5yg",
            "video_category": "robot",
            "platform": "YouTube",
            "title": "05-Putty Grinding Robot",
            "source_name": "Brightmasterrobotics_BMR",
            "access_date": ACCESS,
            "activity_focus": "floor_grinding,surface_preparation",
            "construction_context": "indoor_floor",
            "total_video_duration": "178",
            "visibility_quality": "high",
            "coding_confidence": "medium",
            "inclusion_status": "include",
            "score_relevance": "2",
            "score_visual_clarity": "2",
            "score_activity_continuity": "2",
            "score_activity_identifiability": "2",
            "score_interaction_visibility": "1",
            "score_editing_level": "1",
            "score_parameter_measurability": "2",
            "suitability_total_score": "12",
            "suitability_band": "structured_extraction",
            "notes": "Post-cast putty grinding robot demo",
        },
        {
            "video_id": "R07",
            "video_url": "https://www.youtube.com/watch?v=Z4v3zjiI2lg",
            "video_category": "robot",
            "platform": "YouTube",
            "title": "03-Indoor coating robot NP320",
            "source_name": "Brightmasterrobotics_BMR",
            "access_date": ACCESS,
            "activity_focus": "coating,finishing",
            "construction_context": "indoor_floor",
            "total_video_duration": "215",
            "visibility_quality": "high",
            "coding_confidence": "medium",
            "inclusion_status": "include",
            "score_relevance": "2",
            "score_visual_clarity": "2",
            "score_activity_continuity": "2",
            "score_activity_identifiability": "2",
            "score_interaction_visibility": "1",
            "score_editing_level": "1",
            "score_parameter_measurability": "2",
            "suitability_total_score": "12",
            "suitability_band": "structured_extraction",
            "notes": "Indoor coating robot; supplementary to slab-cycle mapping",
        },
        {
            "video_id": "R08",
            "video_url": "https://www.youtube.com/watch?v=i8RiAKzosyg",
            "video_category": "robot",
            "platform": "YouTube",
            "title": "About BrightMaster Robotics",
            "source_name": "Brightmasterrobotics_BMR",
            "access_date": ACCESS,
            "activity_focus": "company_overview,robot_taxonomy",
            "construction_context": "promotional",
            "total_video_duration": "123",
            "visibility_quality": "medium",
            "coding_confidence": "low",
            "inclusion_status": "qualitative_only",
            "score_relevance": "2",
            "score_visual_clarity": "1",
            "score_activity_continuity": "1",
            "score_activity_identifiability": "1",
            "score_interaction_visibility": "0",
            "score_editing_level": "1",
            "score_parameter_measurability": "1",
            "suitability_total_score": "7",
            "suitability_band": "qualitative_only",
            "notes": "Promotional overview only; no structured segment coding",
        },
        {
            "video_id": "M05",
            "video_url": "https://www.youtube.com/watch?v=CDadY1AMC3U",
            "video_category": "mivan",
            "platform": "YouTube",
            "title": "MIVAN Shuttering Procedure I 7 days Slab Cycle I aluminium formwork",
            "source_name": "Civil Construct",
            "access_date": ACCESS,
            "activity_focus": "slab_cycle,formwork,pour,rebar",
            "construction_context": "high-rise",
            "total_video_duration": "723",
            "visibility_quality": "medium",
            "coding_confidence": "medium",
            "inclusion_status": "include",
            "score_relevance": "2",
            "score_visual_clarity": "2",
            "score_activity_continuity": "1",
            "score_activity_identifiability": "2",
            "score_interaction_visibility": "1",
            "score_editing_level": "1",
            "score_parameter_measurability": "2",
            "suitability_total_score": "11",
            "suitability_band": "structured_extraction",
            "notes": "Parallel alternate upload to M01; segment bounds aligned via scaled M01 transcript",
        },
        {
            "video_id": "T03",
            "video_url": "https://en.bm-robot.com/detail/177.html",
            "video_category": "technical_spec",
            "platform": "manufacturer_website",
            "title": "BrightMaster Floor Grinding Robot",
            "source_name": "BrightMaster",
            "access_date": ACCESS,
            "activity_focus": "floor_grinding",
            "construction_context": "spec_reference",
            "total_video_duration": "n/a",
            "visibility_quality": "n/a",
            "coding_confidence": "high",
            "inclusion_status": "include_specs_only",
            "score_relevance": "2",
            "score_visual_clarity": "n/a",
            "score_activity_continuity": "n/a",
            "score_activity_identifiability": "2",
            "score_interaction_visibility": "n/a",
            "score_editing_level": "n/a",
            "score_parameter_measurability": "2",
            "suitability_total_score": "n/a",
            "suitability_band": "manufacturer_reported_E3",
            "notes": "E3 specs only; not video observation",
        },
        {
            "video_id": "T04",
            "video_url": "https://en.bm-robot.com/detail/192.html",
            "video_category": "technical_spec",
            "platform": "manufacturer_website",
            "title": "BrightMaster Middle East Deployment Case",
            "source_name": "BrightMaster",
            "access_date": ACCESS,
            "activity_focus": "deployment_case,leveling",
            "construction_context": "spec_reference",
            "total_video_duration": "n/a",
            "visibility_quality": "n/a",
            "coding_confidence": "high",
            "inclusion_status": "include_specs_only",
            "score_relevance": "2",
            "score_visual_clarity": "n/a",
            "score_activity_continuity": "n/a",
            "score_activity_identifiability": "2",
            "score_interaction_visibility": "n/a",
            "score_editing_level": "n/a",
            "score_parameter_measurability": "2",
            "suitability_total_score": "n/a",
            "suitability_band": "manufacturer_reported_E3",
            "notes": "E3 deployment claims only; not video observation",
        },
    ]
    meta_rows.extend(new_meta)
    write_csv(DATA / "video_metadata.csv", meta_fields, meta_rows)

    _, seg_rows = read_csv(DATA / "video_segments.csv")
    new_segments = [
        {"segment_id": "R05-S01", "video_id": "R05", "start_time": "00:00:00", "end_time": "00:01:00", "segment_duration_sec": "60", "activity_type": "concrete_finishing", "segment_category": "robot_operation", "segment_quality": "high", "duration_validity": "invalid", "reason_for_rejection": INVALID_DOC},
        {"segment_id": "R06-S01", "video_id": "R06", "start_time": "00:00:00", "end_time": "00:02:58", "segment_duration_sec": "178", "activity_type": "floor_grinding", "segment_category": "robot_operation", "segment_quality": "high", "duration_validity": "invalid", "reason_for_rejection": INVALID_DOC},
        {"segment_id": "R07-S01", "video_id": "R07", "start_time": "00:00:00", "end_time": "00:03:35", "segment_duration_sec": "215", "activity_type": "coating_finishing", "segment_category": "robot_operation", "segment_quality": "high", "duration_validity": "invalid", "reason_for_rejection": INVALID_DOC},
        {"segment_id": "M03-S01", "video_id": "M03", "start_time": "00:00:18", "end_time": "00:02:33", "segment_duration_sec": "135", "activity_type": "formwork_components", "segment_category": "mivan_workflow", "segment_quality": "medium", "duration_validity": "invalid", "reason_for_rejection": INVALID_DOC},
        {"segment_id": "M03-S02", "video_id": "M03", "start_time": "00:02:33", "end_time": "00:06:50", "segment_duration_sec": "257", "activity_type": "formwork_process", "segment_category": "mivan_workflow", "segment_quality": "medium", "duration_validity": "invalid", "reason_for_rejection": INVALID_DOC},
    ]
    m05_segments = [
        ("M05-S01", "00:00:37", "00:01:51", 73, "grid_line_and_thesi"),
        ("M05-S02", "00:01:51", "00:04:00", 129, "vertical_rebar_and_wall_prep"),
        ("M05-S03", "00:04:01", "00:06:58", 176, "wall_panel_erection"),
        ("M05-S04", "00:06:59", "00:07:45", 46, "beam_reinforcement"),
        ("M05-S05", "00:07:46", "00:09:33", 106, "slab_reinforcement"),
        ("M05-S06", "00:09:33", "00:10:01", 27, "electrical_mep"),
        ("M05-S07", "00:10:32", "00:11:20", 48, "slab_supporting_and_quality_check"),
        ("M05-S08", "00:11:24", "00:11:49", 24, "concrete_pour_and_vibration"),
    ]
    for sid, start, end, dur, act in m05_segments:
        new_segments.append(
            {
                "segment_id": sid,
                "video_id": "M05",
                "start_time": start,
                "end_time": end,
                "segment_duration_sec": str(dur),
                "activity_type": act,
                "segment_category": "mivan_workflow",
                "segment_quality": "medium",
                "duration_validity": "invalid",
                "reason_for_rejection": INVALID_M05,
            }
        )
    seg_rows.extend(new_segments)
    write_csv(DATA / "video_segments.csv", list(new_segments[0].keys()), seg_rows)

    _, robot_rows = read_csv(DATA / "robot_video_observations.csv")
    robot_rows.extend(
        [
            {
                "observation_id": "OBS-R05-001",
                "video_id": "R05",
                "segment_id": "R05-S01",
                "robot_activity_type": "concrete_finishing",
                "operating_surface": "hardened_concrete",
                "movement_pattern": "grid-based",
                "guidance_mode": "autonomous",
                "operator_count_visible": "0",
                "assistant_count_visible": "0",
                "setup_visible": "no",
                "setup_complexity": "unknown",
                "operational_continuity": "continuous",
                "interruption_count": "0",
                "obstacle_presence": "no",
                "human_robot_separation": "high",
                "safety_condition": "good",
                "edge_condition": "not_visible",
                "robot_transport_requirement": "unknown",
                "task_duration_observed": "60",
                "duration_validity": "invalid",
                "evidence_level": "E2",
                "coding_confidence": "medium",
            },
            {
                "observation_id": "OBS-R06-001",
                "video_id": "R06",
                "segment_id": "R06-S01",
                "robot_activity_type": "floor_grinding",
                "operating_surface": "hardened_concrete",
                "movement_pattern": "guided",
                "guidance_mode": "autonomous",
                "operator_count_visible": "0",
                "assistant_count_visible": "0",
                "setup_visible": "no",
                "setup_complexity": "unknown",
                "operational_continuity": "continuous",
                "interruption_count": "0",
                "obstacle_presence": "no",
                "human_robot_separation": "high",
                "safety_condition": "good",
                "edge_condition": "not_visible",
                "robot_transport_requirement": "unknown",
                "task_duration_observed": "178",
                "duration_validity": "invalid",
                "evidence_level": "E2",
                "coding_confidence": "medium",
            },
            {
                "observation_id": "OBS-R07-001",
                "video_id": "R07",
                "segment_id": "R07-S01",
                "robot_activity_type": "concrete_finishing",
                "operating_surface": "hardened_concrete",
                "movement_pattern": "grid-based",
                "guidance_mode": "autonomous",
                "operator_count_visible": "0",
                "assistant_count_visible": "0",
                "setup_visible": "no",
                "setup_complexity": "unknown",
                "operational_continuity": "continuous",
                "interruption_count": "0",
                "obstacle_presence": "no",
                "human_robot_separation": "high",
                "safety_condition": "good",
                "edge_condition": "not_visible",
                "robot_transport_requirement": "unknown",
                "task_duration_observed": "215",
                "duration_validity": "invalid",
                "evidence_level": "E2",
                "coding_confidence": "medium",
            },
        ]
    )
    write_csv(DATA / "robot_video_observations.csv", list(robot_rows[0].keys()), robot_rows)

    _, mivan_rows = read_csv(DATA / "mivan_video_observations.csv")
    m05_obs = [
        ("OBS-M05-003", "M05-S03", "formwork", "pre-pour", 6, "wall_panel_erection>deck_panel", 176),
        ("OBS-M05-005", "M05-S05", "rebar", "pre-pour", 6, "slab_reinforcement_with_cover", 106),
        ("OBS-M05-008", "M05-S08", "concrete_pour", "pour", 5, "final_casting>vibration>level_check", 24),
    ]
    for oid, sid, sat, stage, labour, wf, dur in m05_obs:
        mivan_rows.append(
            {
                "observation_id": oid,
                "video_id": "M05",
                "segment_id": sid,
                "slab_activity_type": sat,
                "floor_cycle_stage": stage,
                "labour_count_visible": str(labour),
                "min_visible_labour": str(max(2, labour - 2)),
                "max_visible_labour": str(labour + 2),
                "dominant_visible_labour": str(labour),
                "congestion_level": "high" if labour >= 6 else "medium",
                "reinforcement_complexity": "medium" if sat == "formwork" else "high",
                "conduit_presence": "medium" if stage == "pour" else "unknown",
                "slab_opening_presence": "unknown",
                "access_condition": "congested" if labour >= 6 else "partially_restricted",
                "material_movement_method": "manual" if stage != "pour" else "pump",
                "pour_sequence": "continuous" if stage == "pour" else "unknown",
                "surface_condition": "wet_concrete" if stage == "pour" else "pre-pour",
                "safety_exposure": "high" if stage == "pour" else "medium",
                "edge_protection_visible": "unknown",
                "workflow_sequence": wf,
                "task_duration_observed": str(dur),
                "duration_validity": "invalid",
                "evidence_level": "E2",
                "coding_confidence": "medium",
            }
        )
    mivan_rows.extend(
        [
            {
                "observation_id": "OBS-M03-001",
                "video_id": "M03",
                "segment_id": "M03-S01",
                "slab_activity_type": "formwork",
                "floor_cycle_stage": "pre-pour",
                "labour_count_visible": "2",
                "min_visible_labour": "1",
                "max_visible_labour": "3",
                "dominant_visible_labour": "2",
                "congestion_level": "low",
                "reinforcement_complexity": "low",
                "conduit_presence": "unknown",
                "slab_opening_presence": "unknown",
                "access_condition": "open",
                "material_movement_method": "manual",
                "pour_sequence": "unknown",
                "surface_condition": "pre-pour",
                "safety_exposure": "low",
                "edge_protection_visible": "unknown",
                "workflow_sequence": "component_intro>panel_types>accessories",
                "task_duration_observed": "135",
                "duration_validity": "invalid",
                "evidence_level": "E2",
                "coding_confidence": "medium",
            },
            {
                "observation_id": "OBS-M03-002",
                "video_id": "M03",
                "segment_id": "M03-S02",
                "slab_activity_type": "formwork",
                "floor_cycle_stage": "pre-pour",
                "labour_count_visible": "4",
                "min_visible_labour": "3",
                "max_visible_labour": "6",
                "dominant_visible_labour": "4",
                "congestion_level": "medium",
                "reinforcement_complexity": "medium",
                "conduit_presence": "unknown",
                "slab_opening_presence": "unknown",
                "access_condition": "partially_restricted",
                "material_movement_method": "manual",
                "pour_sequence": "unknown",
                "surface_condition": "pre-pour",
                "safety_exposure": "medium",
                "edge_protection_visible": "unknown",
                "workflow_sequence": "assembly>erection>alignment",
                "task_duration_observed": "257",
                "duration_validity": "invalid",
                "evidence_level": "E2",
                "coding_confidence": "medium",
            },
        ]
    )
    write_csv(DATA / "mivan_video_observations.csv", list(mivan_rows[0].keys()), mivan_rows)

    _, cleaned_rows = read_csv(DATA / "cleaned_video_dataset.csv")
    cleaned_rows.extend(
        [
            {
                "observation_id": "OBS-R05-001",
                "video_id": "R05",
                "segment_id": "R05-S01",
                "video_category": "robot",
                "activity_type": "concrete_finishing",
                "workflow_stage": "post-cast",
                "labour_count_visible": "",
                "robot_operator_count": "0",
                "movement_pattern": "grid-based",
                "operating_surface": "hardened_concrete",
                "congestion_level": "low",
                "reinforcement_complexity": "",
                "access_condition": "open",
                "safety_condition": "good",
                "task_duration_observed": "60",
                "duration_validity": "invalid",
                "evidence_level": "E2",
                "coding_confidence": "medium",
                "source_type": "video-estimated",
                "visibility_quality": "high",
            },
            {
                "observation_id": "OBS-R06-001",
                "video_id": "R06",
                "segment_id": "R06-S01",
                "video_category": "robot",
                "activity_type": "floor_grinding",
                "workflow_stage": "post-cast",
                "labour_count_visible": "",
                "robot_operator_count": "0",
                "movement_pattern": "guided",
                "operating_surface": "hardened_concrete",
                "congestion_level": "low",
                "reinforcement_complexity": "",
                "access_condition": "open",
                "safety_condition": "good",
                "task_duration_observed": "178",
                "duration_validity": "invalid",
                "evidence_level": "E2",
                "coding_confidence": "medium",
                "source_type": "video-estimated",
                "visibility_quality": "high",
            },
            {
                "observation_id": "OBS-M03-002",
                "video_id": "M03",
                "segment_id": "M03-S02",
                "video_category": "mivan",
                "activity_type": "formwork_process",
                "workflow_stage": "pre-pour",
                "labour_count_visible": "4",
                "robot_operator_count": "",
                "movement_pattern": "",
                "operating_surface": "",
                "congestion_level": "medium",
                "reinforcement_complexity": "medium",
                "access_condition": "partially_restricted",
                "safety_condition": "moderate",
                "task_duration_observed": "257",
                "duration_validity": "invalid",
                "evidence_level": "E2",
                "coding_confidence": "medium",
                "source_type": "video-estimated",
                "visibility_quality": "high",
            },
            {
                "observation_id": "OBS-M05-003",
                "video_id": "M05",
                "segment_id": "M05-S03",
                "video_category": "mivan",
                "activity_type": "wall_panel_erection",
                "workflow_stage": "pre-pour",
                "labour_count_visible": "6",
                "robot_operator_count": "",
                "movement_pattern": "",
                "operating_surface": "",
                "congestion_level": "high",
                "reinforcement_complexity": "medium",
                "access_condition": "congested",
                "safety_condition": "moderate",
                "task_duration_observed": "176",
                "duration_validity": "invalid",
                "evidence_level": "E2",
                "coding_confidence": "medium",
                "source_type": "video-estimated",
                "visibility_quality": "medium",
            },
        ]
    )
    write_csv(DATA / "cleaned_video_dataset.csv", list(cleaned_rows[0].keys()), cleaned_rows)

    spec_fields = [
        "spec_id",
        "source_id",
        "source_url",
        "robot_or_process",
        "parameter_name",
        "parameter_value",
        "unit",
        "evidence_level",
        "notes",
    ]
    specs = [
        ("SPEC-T01-01", "T01", "https://en.bm-robot.com/detail/173.html", "concrete_leveling_robot", "model_width_options", "1.5;2.5", "m", "E3", "manufacturer-reported"),
        ("SPEC-T01-02", "T01", "https://en.bm-robot.com/detail/173.html", "concrete_leveling_robot", "operating_efficiency", "160;300", "m2/h", "E3", "manufacturer-reported"),
        ("SPEC-T01-03", "T01", "https://en.bm-robot.com/detail/173.html", "concrete_leveling_robot", "guidance_mode", "remote_control", "categorical", "E3", "manufacturer-reported"),
        ("SPEC-T02-01", "T02", "https://en.bm-robot.com/detail/174.html", "concrete_finishing_robot", "operating_efficiency", "300", "m2/h", "E3", "manufacturer-reported"),
        ("SPEC-T02-02", "T02", "https://en.bm-robot.com/detail/174.html", "concrete_finishing_robot", "guidance_mode", "autonomous;remote_control", "categorical", "E3", "SLAM navigation reported"),
        ("SPEC-T03-01", "T03", "https://en.bm-robot.com/detail/177.html", "floor_grinding_robot", "navigation", "LiDAR;autonomous_path_planning", "categorical", "E3", "manufacturer-reported"),
        ("SPEC-T04-01", "T04", "https://en.bm-robot.com/detail/192.html", "deployment_case", "completed_area", "3000", "m2", "E3", "Abu Dhabi and RAK Central with ALEC"),
        ("SPEC-T04-02", "T04", "https://en.bm-robot.com/detail/192.html", "deployment_case", "operators_trained", "20", "count", "E3", "manufacturer-reported"),
        ("SPEC-T04-03", "T04", "https://en.bm-robot.com/detail/192.html", "deployment_case", "flatness_tolerance", "3", "mm", "E3", "plus_minus reported"),
        ("SPEC-T04-04", "T04", "https://en.bm-robot.com/detail/192.html", "deployment_case", "manpower_reduction_claim", "30", "percent", "E3", "manufacturer-reported"),
    ]
    write_csv(
        DATA / "manufacturer_specs.csv",
        spec_fields,
        [
            {
                "spec_id": s[0],
                "source_id": s[1],
                "source_url": s[2],
                "robot_or_process": s[3],
                "parameter_name": s[4],
                "parameter_value": s[5],
                "unit": s[6],
                "evidence_level": s[7],
                "notes": s[8],
            }
            for s in specs
        ],
    )
    print("Batch update complete.")


if __name__ == "__main__":
    main()
