"""Check CSV, YAML, Python, and Markdown files for minified/single-line formatting."""

from __future__ import annotations

import ast
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SKIP_DIRS = {".git", "__pycache__", ".pytest_cache", "node_modules"}
EXTENSIONS = {".csv", ".py", ".yaml", ".yml", ".md"}
REPORT_PATH = ROOT / "reports" / "file_formatting_report.md"


def should_scan(path: Path) -> bool:
    return path.suffix in EXTENSIONS and not any(part in SKIP_DIRS for part in path.parts)


def check_file(path: Path) -> list[str]:
    issues: list[str] = []
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        return [f"unreadable: {exc}"]
    lines = text.splitlines()
    rel = path.relative_to(ROOT)
    if len(lines) <= 3 and len(text) > 1000:
        issues.append(f"possible single-line file ({len(lines)} lines, {len(text)} chars)")
    if path.suffix == ".py":
        try:
            ast.parse(text)
        except SyntaxError as exc:
            issues.append(f"Python syntax error: {exc}")
    if path.suffix in {".yaml", ".yml"}:
        try:
            import yaml

            yaml.safe_load(text)
        except Exception as exc:  # noqa: BLE001
            issues.append(f"YAML parse error: {exc}")
    if path.suffix == ".csv" and lines and len(lines[0]) > 5000:
        issues.append("CSV header line unusually long")
    return [f"{rel}: {msg}" for msg in issues]


def main() -> int:
    findings: list[str] = []
    scanned = 0
    for path in sorted(ROOT.rglob("*")):
        if not path.is_file() or not should_scan(path):
            continue
        scanned += 1
        findings.extend(check_file(path))

    lines = [
        "# File Formatting Report",
        "",
        f"Generated by `scripts/check_file_formatting.py`",
        "",
        f"- Files scanned: {scanned}",
        f"- Issues found: {len(findings)}",
        "",
    ]
    if findings:
        lines.append("## Issues")
        lines.append("")
        lines.extend(f"- {item}" for item in findings)
    else:
        lines.append("No formatting issues detected.")
    lines.append("")
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Scanned {scanned} files; {len(findings)} issues.")
    print(f"Report: {REPORT_PATH}")
    for item in findings:
        print(f"  {item}")
    return 1 if findings else 0


if __name__ == "__main__":
    raise SystemExit(main())
