"""Seed priority video registry from the suitability review document."""

from __future__ import annotations

import csv
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "video_metadata.csv"

ACCESS_DATE = date.today().isoformat()

ROWS = [
    {
        "video_id": "R01",
        "video_url": "https://www.youtube.com/@Brightmasterrobotics_BMR/videos",
        "video_category": "robot",
        "platform": "YouTube",
        "title": "BrightMaster Robotics Official Channel",
        "source_name": "BrightMaster Robotics",
        "access_date": ACCESS_DATE,
        "activity_focus": "leveling,finishing,grinding,multi-robot",
        "construction_context": "mixed",
        "total_video_duration": "",
        "visibility_quality": "",
        "coding_confidence": "",
        "inclusion_status": "pending_screening",
        "score_relevance": "",
        "score_visual_clarity": "",
        "score_activity_continuity": "",
        "score_activity_identifiability": "",
        "score_interaction_visibility": "",
        "score_editing_level": "",
        "score_parameter_measurability": "",
        "suitability_total_score": "",
        "suitability_band": "",
        "notes": "Primary robot source pool; screen each video individually",
    },
    {
        "video_id": "R02",
        "video_url": "https://www.youtube.com/shorts/ICOBNE0471E",
        "video_category": "robot",
        "platform": "YouTube",
        "title": "Floor Leveling Robot Working",
        "source_name": "BrightMaster Robotics",
        "access_date": ACCESS_DATE,
        "activity_focus": "concrete_leveling",
        "construction_context": "slab",
        "total_video_duration": "",
        "visibility_quality": "",
        "coding_confidence": "",
        "inclusion_status": "pending_screening",
        "score_relevance": "",
        "score_visual_clarity": "",
        "score_activity_continuity": "",
        "score_activity_identifiability": "",
        "score_interaction_visibility": "",
        "score_editing_level": "",
        "score_parameter_measurability": "",
        "suitability_total_score": "",
        "suitability_band": "",
        "notes": "Short clip; qualitative or partial timing only",
    },
    {
        "video_id": "R03",
        "video_url": "https://www.youtube.com/watch?v=2Mlp_fRBfD0",
        "video_category": "robot",
        "platform": "YouTube",
        "title": "Concrete Floor Smoothing Robot",
        "source_name": "unknown",
        "access_date": ACCESS_DATE,
        "activity_focus": "concrete_finishing",
        "construction_context": "slab",
        "total_video_duration": "",
        "visibility_quality": "",
        "coding_confidence": "",
        "inclusion_status": "pending_screening",
        "score_relevance": "",
        "score_visual_clarity": "",
        "score_activity_continuity": "",
        "score_activity_identifiability": "",
        "score_interaction_visibility": "",
        "score_editing_level": "",
        "score_parameter_measurability": "",
        "suitability_total_score": "",
        "suitability_band": "",
        "notes": "Verify manufacturer before robot-side coding",
    },
    {
        "video_id": "R04",
        "video_url": "https://www.facebook.com/61583714351020/videos/concrete-leveling-robot-works-at-any-height/938901825735810/",
        "video_category": "robot",
        "platform": "Facebook",
        "title": "Concrete Leveling Robot Works at Any Height",
        "source_name": "BrightMaster",
        "access_date": ACCESS_DATE,
        "activity_focus": "transport,lifting,leveling",
        "construction_context": "high-rise",
        "total_video_duration": "",
        "visibility_quality": "",
        "coding_confidence": "",
        "inclusion_status": "pending_screening",
        "score_relevance": "",
        "score_visual_clarity": "",
        "score_activity_continuity": "",
        "score_activity_identifiability": "",
        "score_interaction_visibility": "",
        "score_editing_level": "",
        "score_parameter_measurability": "",
        "suitability_total_score": "",
        "suitability_band": "",
        "notes": "Supplementary; less stable citation than YouTube",
    },
    {
        "video_id": "T01",
        "video_url": "https://en.bm-robot.com/detail/173.html",
        "video_category": "technical_spec",
        "platform": "manufacturer_website",
        "title": "BrightMaster Concrete Leveling Robot",
        "source_name": "BrightMaster",
        "access_date": ACCESS_DATE,
        "activity_focus": "concrete_leveling",
        "construction_context": "spec_reference",
        "total_video_duration": "n/a",
        "visibility_quality": "n/a",
        "coding_confidence": "high",
        "inclusion_status": "include_specs_only",
        "score_relevance": "2",
        "score_visual_clarity": "n/a",
        "score_activity_continuity": "n/a",
        "score_activity_identifiability": "2",
        "score_interaction_visibility": "n/a",
        "score_editing_level": "n/a",
        "score_parameter_measurability": "2",
        "suitability_total_score": "n/a",
        "suitability_band": "manufacturer_reported_E3",
        "notes": "E3 specs only; not video observation",
    },
    {
        "video_id": "T02",
        "video_url": "https://en.bm-robot.com/detail/174.html",
        "video_category": "technical_spec",
        "platform": "manufacturer_website",
        "title": "BrightMaster Concrete Finishing Robot",
        "source_name": "BrightMaster",
        "access_date": ACCESS_DATE,
        "activity_focus": "concrete_finishing",
        "construction_context": "spec_reference",
        "total_video_duration": "n/a",
        "visibility_quality": "n/a",
        "coding_confidence": "high",
        "inclusion_status": "include_specs_only",
        "score_relevance": "2",
        "score_visual_clarity": "n/a",
        "score_activity_continuity": "n/a",
        "score_activity_identifiability": "2",
        "score_interaction_visibility": "n/a",
        "score_editing_level": "n/a",
        "score_parameter_measurability": "2",
        "suitability_total_score": "n/a",
        "suitability_band": "manufacturer_reported_E3",
        "notes": "E3 specs only; not video observation",
    },
    {
        "video_id": "M01",
        "video_url": "https://www.youtube.com/watch?v=tuk1yi-lEwo",
        "video_category": "mivan",
        "platform": "YouTube",
        "title": "MIVAN Shuttering Procedure | 7 Days Slab Cycle",
        "source_name": "unknown",
        "access_date": ACCESS_DATE,
        "activity_focus": "slab_cycle,formwork,pour,rebar",
        "construction_context": "high-rise",
        "total_video_duration": "",
        "visibility_quality": "",
        "coding_confidence": "",
        "inclusion_status": "pending_screening",
        "score_relevance": "",
        "score_visual_clarity": "",
        "score_activity_continuity": "",
        "score_activity_identifiability": "",
        "score_interaction_visibility": "",
        "score_editing_level": "",
        "score_parameter_measurability": "",
        "suitability_total_score": "",
        "suitability_band": "",
        "notes": "Best candidate for Mivan workflow sequence",
    },
    {
        "video_id": "M02",
        "video_url": "https://www.youtube.com/watch?v=AiTlMoNKdNk",
        "video_category": "mivan",
        "platform": "YouTube",
        "title": "MIVAN Shuttering Process: From Start to Finish",
        "source_name": "unknown",
        "access_date": ACCESS_DATE,
        "activity_focus": "formwork,rebar,slab_cycle",
        "construction_context": "high-rise",
        "total_video_duration": "",
        "visibility_quality": "",
        "coding_confidence": "",
        "suitability_band": "",
        "inclusion_status": "pending_screening",
        "score_relevance": "",
        "score_visual_clarity": "",
        "score_activity_continuity": "",
        "score_activity_identifiability": "",
        "score_interaction_visibility": "",
        "score_editing_level": "",
        "score_parameter_measurability": "",
        "suitability_total_score": "",
        "notes": "Core Mivan stage mapping",
    },
    {
        "video_id": "M03",
        "video_url": "https://www.youtube.com/watch?v=tBguN9TTEYQ",
        "video_category": "mivan",
        "platform": "YouTube",
        "title": "Mivan Formwork / Mivan Shuttering / Aluminium Formwork",
        "source_name": "unknown",
        "access_date": ACCESS_DATE,
        "activity_focus": "formwork,finish_quality",
        "construction_context": "high-rise",
        "total_video_duration": "",
        "visibility_quality": "",
        "coding_confidence": "",
        "inclusion_status": "pending_screening",
        "score_relevance": "",
        "score_visual_clarity": "",
        "score_activity_continuity": "",
        "score_activity_identifiability": "",
        "score_interaction_visibility": "",
        "score_editing_level": "",
        "score_parameter_measurability": "",
        "suitability_total_score": "",
        "suitability_band": "",
        "notes": "Use if continuous activity is visible",
    },
    {
        "video_id": "M04",
        "video_url": "https://www.youtube.com/playlist?list=PLo4LD64ASBprAVBlA2q0p0F2eljYqZycR",
        "video_category": "mivan",
        "platform": "YouTube",
        "title": "Aluminium Formwork / MIVAN Technology Playlist",
        "source_name": "unknown",
        "access_date": ACCESS_DATE,
        "activity_focus": "formwork,workflow_pool",
        "construction_context": "high-rise",
        "total_video_duration": "",
        "visibility_quality": "",
        "coding_confidence": "",
        "inclusion_status": "pending_screening",
        "score_relevance": "",
        "score_visual_clarity": "",
        "score_activity_continuity": "",
        "score_activity_identifiability": "",
        "score_interaction_visibility": "",
        "score_editing_level": "",
        "score_parameter_measurability": "",
        "suitability_total_score": "",
        "suitability_band": "",
        "notes": "Expand registry after core set is coded",
    },
]

FIELDNAMES = list(ROWS[0].keys())


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=FIELDNAMES)
        writer.writeheader()
        writer.writerows(ROWS)
    print(f"Seeded {len(ROWS)} registry rows to {OUT}")


if __name__ == "__main__":
    main()
